name = "vkomari-cf"
main = "src/index.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "vkomari-db"
database_id = "a6e0fc08-1a9d-4e18-b401-741ffad42900"

[triggers]
crons = ["* * * * *"]
